name: nasa
description: The easiest and powerful Dart/Flutter library for NASA APIs.
version: 0.0.4
repository: https://github.com/myConsciousness/nasa-api
issue_tracker: https://github.com/myConsciousness/nasa-api/issues

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  universal_io: ^2.2.0
  intl: ^0.19.0


dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  mockito: ^5.4.0

import_sorter:
  emojis: true
