name: nasa_api
description: The easiest and powerful Dart/Flutter library for NASA APIs.
version: 0.0.1
repository: https://github.com/myConsciousness/nasa-api
issue_tracker: https://github.com/myConsciousness/nasa-api/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  universal_io: ^2.0.4


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  mockito: ^5.3.2

import_sorter:
  emojis: true
